name: safirisha
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1
  cloud_firestore: ^2.2.2
  firebase_storage: ^9.0.0
  google_fonts: ^2.1.0
  shared_preferences: ^2.0.6
  simple_animations: ^1.3.3
  otp_text_field: ^1.1.1
  flutter_spinkit: ^4.1.2
  font_awesome_flutter: ^9.1.0
  image_picker: ^0.8.1+3
  image_cropper: ^1.4.1
  modal_bottom_sheet: ^2.0.0
  measured_size: ^1.0.0
  firebase_messaging: ^10.0.4
  url_launcher: ^6.0.9
  cached_network_image: ^2.1.0+1
  carousel_slider: ^4.0.0
  http: ^0.13.3
  google_maps_place_picker: ^2.0.0-nullsafety.3
  geolocator: ^7.4.0
  dio: ^4.0.0
  google_maps_flutter: ^2.0.8
  flutter_polyline_points: ^1.0.0
  flutter_datetime_picker: ^1.5.1
  location: ^4.3.0
  intl: ^0.17.0
  toggle_switch: ^1.2.0
  syncfusion_flutter_sliders: ^19.2.57
  chips_choice: ^2.0.1
  flutterwave: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
